clear all

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Box Sync\CHEETA UIUC Only\Notes\EGW\Actual Work\008\carrier.csv
%
% Auto-generated by MATLAB on 21-Jun-2021 12:24:51

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["DEPARTURES_PERFORMED", "PAYLOAD", "Pld", "PASSENGERS", "FREIGHT", "DISTANCE", "UNIQUE_CARRIER_NAME", "AIRCRAFT_TYPE", "MONTH"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "categorical", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "UNIQUE_CARRIER_NAME", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("D:\Box Sync\CHEETA UIUC Only\Notes\EGW\Actual Work\008\carrier_swa.csv", opts);

%% Convert to output type
DEPARTURES_PERFORMED = tbl.DEPARTURES_PERFORMED;
PAYLOAD = tbl.PAYLOAD;
Pld = tbl.Pld;
PASSENGERS = tbl.PASSENGERS;
FREIGHT = tbl.FREIGHT;
DISTANCE = tbl.DISTANCE;
UNIQUE_CARRIER_NAME = tbl.UNIQUE_CARRIER_NAME;
AIRCRAFT_TYPE = tbl.AIRCRAFT_TYPE;
MONTH = tbl.MONTH;

%% Clear temporary variables
clear opts tbl

%% Actual work

Cdst = [3904.156752
3843.396893
3778.848525
3708.886504
3641.679523
3570.814848
3500.94307
3435.358557
3369.867943
3299.004825
3238.467532
3165.367681
3097.950478
3024.344914
2949.185594
2463.359511
1978.800775
1503.229135
1042.434445
0];

Cpay = [0
2500
5000
7500
10000
12500
15000
17500
20000
22500
25000
27500
30000
32500
35000
37500
40000
42500
45000
47500];

Bdst = [0
2150
2950
3700];


Bpay = [45188
45188
35000
0];



p = plot(DISTANCE,Pld,Cdst,Cpay, Bdst, Bpay)
p(1).Marker = 'x'
p(1).LineStyle = 'none'
