function [tc23, mdes, dcdc] = importfig10(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TC23, MDES, VARNAME3, DCDC1, DCDC2, DCDC3, DCDC4, DCDC5, DCDC6,
%  DCDC7] = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as column vectors.
%
%  [TC23, MDES, VARNAME3, DCDC1, DCDC2, DCDC3, DCDC4, DCDC5, DCDC6,
%  DCDC7] = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [tc23, mdes, VarName3, dcdc1, dcdc2, dcdc3, dcdc4, dcdc5, dcdc6, dcdc7] = importfile("C:\Users\Elias.DESKTOP-57LHO0I\Box Sync\CHEETA UIUC Only\Notes\EGW\Actual Work\fig10.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2020 14:46:34

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["tc23", "mdes", "VarName3", "dcdc1", "dcdc2", "dcdc3", "dcdc4", "dcdc5", "dcdc6", "dcdc7"];
opts.VariableTypes = ["double", "double", "string", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName3", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
tc23 = tbl.tc23;
tc23 = tc23(1:7);
mdes = tbl.mdes;
dcdc = [tbl.dcdc1,tbl.dcdc2,tbl.dcdc3,tbl.dcdc4,tbl.dcdc5,tbl.dcdc6,tbl.dcdc7];
end