function [SbSpi, Mach, Cdpi] = importfig13(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [SBSPI, MACH, VARNAME3, CDPI1, CDPI2, CDPI3, CDPI4] =
%  IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [SBSPI, MACH, VARNAME3, CDPI1, CDPI2, CDPI3, CDPI4] =
%  IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [SbSpi, Mach, VarName3, Cdpi1, Cdpi2, Cdpi3, Cdpi4] = importfile("C:\Users\Elias.DESKTOP-57LHO0I\Box Sync\CHEETA UIUC Only\Notes\EGW\Actual Work\fig13.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2020 15:12:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SbSpi", "Mach", "VarName3", "Cdpi1", "Cdpi2", "Cdpi3", "Cdpi4"];
opts.VariableTypes = ["double", "double", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName3", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
SbSpi = tbl.SbSpi;
SbSpi = SbSpi(1:4);
Mach = tbl.Mach;
% Mach = Mach(1:4);
Cdpi = [tbl.Cdpi1,tbl.Cdpi2,tbl.Cdpi3,tbl.Cdpi4];
end