function [CLdesin, tc23, M2D2D1out] = importfig3(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [CLD, TC2T3, VARNAME3, M2D1, M2D2, M2D3, M2D4, M2D5, M2D6, M2D7,
%  M2D8] = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as column vectors.
%
%  [CLD, TC2T3, VARNAME3, M2D1, M2D2, M2D3, M2D4, M2D5, M2D6, M2D7,
%  M2D8] = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [CLd, tc2t3, VarName3, M2D1, M2D2, M2D3, M2D4, M2D5, M2D6, M2D7, M2D8] = importfile("C:\Users\Elias.DESKTOP-57LHO0I\Box Sync\CHEETA UIUC Only\Notes\EGW\Actual Work\fig3.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Mar-2020 10:13:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["CLd", "tc2t3", "VarName3", "M2D1", "M2D2", "M2D3", "M2D4", "M2D5", "M2D6", "M2D7", "M2D8"];
opts.VariableTypes = ["double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["CLd", "tc2t3", "M2D1", "M2D2", "M2D3", "M2D4", "M2D5", "M2D6", "M2D7", "M2D8"], "FillValue", 0);

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
CLd = tbl.CLd;
CLdesin = CLd(1:8);
tc23 = tbl.tc2t3;
M2D2D1out = tbl.M2D1;
M2D2D1out = [M2D2D1out,tbl.M2D2];
M2D2D1out = [M2D2D1out,tbl.M2D3];
M2D2D1out = [M2D2D1out,tbl.M2D4];
M2D2D1out = [M2D2D1out,tbl.M2D5];
M2D2D1out = [M2D2D1out,tbl.M2D6];
M2D2D1out = [M2D2D1out,tbl.M2D7];
M2D2D1out = [M2D2D1out,tbl.M2D8];
end